{% set version = "0.0.12.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-inspectdf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/inspectdf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/inspectdf/inspectdf_{{ version }}.tar.gz
  sha256: 356ff9b5dc2ba80e53fd961bf1b252dba8eee0fd6fd25b46b4d3351b382a7c29

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr
    - r-ggfittext
    - r-ggplot2
    - r-magrittr
    - r-progress
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-rcpp
    - r-dplyr
    - r-ggfittext
    - r-ggplot2
    - r-magrittr
    - r-progress
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('inspectdf')"           # [not win]
    - "\"%R%\" -e \"library('inspectdf')\""  # [win]

about:
  home: https://alastairrushworth.github.io/inspectdf/
  license: GPL-2.0-only
  summary: A collection of utilities for columnwise summary, comparison and visualisation of data frames.  Functions report missingness, categorical levels, numeric distribution, correlation, column types and memory usage.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: inspectdf
# Title: Inspection, Comparison and Visualisation of Data Frames
# Version: 0.0.10
# Authors@R: c( person("Alastair", "Rushworth", email = "alastairmrushworth@gmail.com", role = c("aut", "cre")), person("David", "Wilkins", email = "david@wilkox.org", role = "ctb") )
# Maintainer: Alastair Rushworth <alastairmrushworth@gmail.com>
# Description: A collection of utilities for columnwise summary, comparison and visualisation of data frames.  Functions report missingness, categorical levels, numeric distribution, correlation, column types and memory usage.
# Language: en_GB
# LinkingTo: Rcpp
# LazyLoad: yes
# LazyData: true
# ByteCompile: yes
# Encoding: UTF-8
# Depends: R (>= 3.5.0)
# Imports: dplyr, ggplot2, ggfittext, magrittr, progress, Rcpp, tibble, tidyr
# Suggests: testthat
# License: GPL-2
# URL: https://alastairrushworth.github.io/inspectdf/
# BugReports: https://github.com/alastairrushworth/inspectdf/issues
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2021-02-20 14:25:36 UTC; alastairrushworth
# Author: Alastair Rushworth [aut, cre], David Wilkins [ctb]
# Repository: CRAN
# Date/Publication: 2021-02-20 14:50:03 UTC
